- name: sliverserver-playbook
  hosts: "{{ sliverserverip }}"
  tasks:
    - name: zip sliver (local)
      local_action: ansible.builtin.command zip -r sliver.zip sliver
    - name: upload sliver.zip
      become: yes
      ansible.builtin.copy:
        src: sliver.zip
        dest: /opt/
    - name: delete sliver.zip (local)
      local_action: ansible.builtin.command rm sliver.zip
    - name: unzip sliver.zip
      become: yes
      ansible.builtin.command:
        cmd: unzip -u sliver.zip
        chdir: /opt
    - name: change perms
      become: yes
      ansible.builtin.command:
        cmd: chmod +x /opt/sliver/sliver-server
    - name: remove operator files
      become: yes
      ansible.builtin.command:
        cmd: rm -rf /opt/sliver/builder.cfg
    - name: create operator file
      become: yes
      ansible.builtin.command:
        cmd: /opt/sliver/sliver-server operator -l {{ sliverserverip }} -p 31337 -n operator -s /opt/sliver/operator.cfg
    - name: create builder operator file (aws windows machine)
      become: yes
      ansible.builtin.command:
        cmd: /opt/sliver/sliver-server operator -l 172.31.0.5 -p 31337 -n builder_aws -s /opt/sliver/builder_aws.cfg
    - name: create builder operator file (local windows machine)
      become: yes
      ansible.builtin.command:
        cmd: /opt/sliver/sliver-server operator -l {{ sliverserverip }} -p 31337 -n builder_local -s /opt/sliver/builder_local.cfg
    - name: change builder perms (aws windows machine)
      become: yes
      ansible.builtin.command:
        cmd: chmod +r /opt/sliver/builder.cfg
    - name: change builder perms (local windows machine)
      become: yes
      ansible.builtin.command:
        cmd: chmod +r /opt/sliver/builder_local.cfg
    - name: change operator perms
      become: yes
      ansible.builtin.command:
        cmd: chmod +r /opt/sliver/operator.cfg
    - name: download operator file
      ansible.builtin.fetch:
        src: /opt/sliver/operator.cfg
        dest: ./operator.cfg
        flat: yes
    - name: download sliver builder operator file (aws windows machine)
      ansible.builtin.fetch:
        src: /opt/sliver/builder_aws.cfg
        dest: ./builder_aws.cfg
        flat: yes
    - name: download sliver builder operator file (local windows machine)
      ansible.builtin.fetch:
        src: /opt/sliver/builder_local.cfg
        dest: ./builder_local.cfg
        flat: yes
    - name: remove operator files
      become: yes
      ansible.builtin.command:
        cmd: rm /opt/sliver/operator.cfg /opt/sliver/builder.cfg /opt/sliver/builder_local.cfg
    - name: start sliver daemon mode
      become: yes
      shell: "/opt/sliver/sliver-server daemon &"
      async: 45
      poll: 0
