- name: sliverserver-playbook
  hosts: "{{ sliverserverip }}"
  tasks:
    - name: Copy sliver server
      become: yes
#      ansible.builtin.copy:
#        src: ./sliver
#        dest: /opt/
#        directory_mode: 1
      ansible.builtin.command:
        cmd: aws s3 cp --recursive s3://sliver-bucket/sliver /opt/sliver
    - name: change perms
      become: yes
      ansible.builtin.command:
        cmd: chmod +x /opt/sliver/sliver-server
    - name: create operator file
      become: yes
      ansible.builtin.command:
        cmd: /opt/sliver/sliver-server operator -l {{ sliverserverip }} -p 31337 -n operator -s /opt/sliver/operator.cfg
    - name: create builder operator file
      become: yes
      ansible.builtin.command:
        cmd: /opt/sliver/sliver-server operator -l 172.31.0.5 -p 31337 -n operator -s /opt/sliver/builder.cfg
    - name: change operator perms
      become: yes
      ansible.builtin.command:
        cmd: chmod +r /opt/sliver/builder.cfg
    - name: change operator perms
      become: yes
      ansible.builtin.command:
        cmd: chmod +r /opt/sliver/operator.cfg
    - name: download operator file
      ansible.builtin.fetch:
        src: /opt/sliver/operator.cfg
        dest: ./operator.cfg
        flat: yes
    - name: download sliver builder operator file
      ansible.builtin.fetch:
        src: /opt/sliver/builder.cfg
        dest: ./builder.cfg
        flat: yes
    - name: remove operator files
      become: yes
      ansible.builtin.command:
        cmd: rm /opt/sliver/operator.cfg /opt/sliver/builder.cfg
    - name: start sliver daemon mode
      become: yes
      shell: "/opt/sliver/sliver-server daemon &"
      async: 45
      poll: 0
